name: "Aspect"
description: "Aspect is a compiling template engine for Lua and LuaJIT."
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io/"
exclude:
  - src
  - bin
remote_theme: bzick/jekyll-docs-theme
analytics:
  google: UA-164241665-1
  yandex: 64680703

# theme configuration
# #373737 #EE722E

ui:
  mode: 'light'
#  header:
#    light:
#      color1: "#373737"
#      color2: "#EE722E"
#      trianglify: true

project:
  version: 2.2
  download_url: https://github.com/unifire-app/aspect/releases
  download_text: Download

license:
  software: BSD 3 Clause
  software_url: https://opensource.org/licenses/BSD-3-Clause

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  pages:
    - title: Syntax
      url: ./syntax.html
    - title: Tags
      url: ./tags.html
    - title: Filters
      url: ./filters.html
    - title: Funcs
      url: ./funcs.html
    - title: Tests
      url: ./tests.html
    - title: Spec
      url: ./spec.html
    - title: API
      url: ./api.html
    - title: CLI
      url: ./cli.html
  header:
    - title: '<img src="https://travis-ci.org/unifire-app/aspect.svg?branch=master" />'
      url: https://travis-ci.org/unifire-app/aspect
    - title: '<img src="https://codecov.io/gh/unifire-app/aspect/branch/master/graph/badge.svg" />'
      url: https://codecov.io/gh/unifire-app/aspect
    - title: '<img src="/aspect/assets/luarocks.svg" />'
      url: https://luarocks.org/modules/unifire/aspect
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/unifire-app/aspect
    - title: Issues
      icon: bug
      url: https://github.com/unifire-app/aspect/issues?state=open
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/unifire-app/aspect
social:
  github:
    user: unifire-app
    repo: aspect

icons:
  favicon: /aspect/assets/aspect.png
